### alink_drone settings ###

### allow alink to set power
allow_set_power=1
# read chosen card from wfb.yaml, load it's power tables and use them
use_0_to_4_txpower=1
# set desired power output (0 pitmode, 4 highest power)(scales with MCS)
power_level_0_to_4=0

### load ldpc and stbc from wfb.yaml
get_card_info_from_yaml=1

### if gs heartbeat lost for x ms, apply fallback profile
fallback_ms=1000

### Fallback profile – applied when GS heartbeat is lost
fallback_gi=long
fallback_mcs=1
fallback_feck=8
fallback_fecn=12
fallback_bitrate=4096
fallback_gop=1
fallback_power=58
fallback_roiqp=0,0,0,0
fallback_bandwidth=20
fallback_qpdelta=0

### allow lost GS packet to request new keyframe
allow_request_keyframe=1
# allow drone driver-tx_dropped to request new keyframe
allow_rq_kf_by_tx_d=1
# how often to check driver-xtx
check_xtx_period_ms=2250
# limit time between keyframe requests
request_keyframe_interval_ms=1112
# request a keyframe at every link change
idr_every_change=0

### enable higher quality in center of image
roi_focus_mode=0

### attempt to help encoder bitrate spikes by strategically lowering FPS when on high resolutions
allow_spike_fix_fps=0
# reduce bitrate on driver-tx dropped for 1 second or until xtx stops
allow_xtx_reduce_bitrate=1
# reduce bitrate to
xtx_reduce_bitrate_factor=0.8

### how much info on OSD (0 to 6). 4 = all on one line. 6 = all on multiple lines
osd_level=0
# make custom text smaller/bigger
multiply_font_size_by=1

### Command templates – Don't change these unless you know what you are doing
powerCommandTemplate="iw dev wlan0 set txpower fixed {power}"
#powerCommandTemplate="tx_manager.sh set_tx_power {power}"
fpsCommandTemplate="echo 'setfps 0 {fps}' > /proc/mi_modules/mi_sensor/mi_sensor0"
qpDeltaCommandTemplate="curl localhost/api/v1/set?video0.qpDelta={qpDelta}"
mcsCommandTemplate="wfb_tx_cmd 8000 set_radio -B {bandwidth} -G {gi} -S {stbc} -L {ldpc} -M {mcs}"
bitrateCommandTemplate="curl -s 'http://localhost/api/v1/set?video0.bitrate={bitrate}'"
gopCommandTemplate="curl -s 'http://localhost/api/v1/set?video0.gopSize={gop}'"
fecCommandTemplate="wfb_tx_cmd 8000 set_fec -k {fecK} -n {fecN}"
roiCommandTemplate="curl -s 'http://localhost/api/v1/set?fpv.roiQp={roiQp}'"
idrCommandTemplate="curl localhost/request/idr"
customOSD=&L%d0&F%d&B CPU:&C,&Tc TX:&Wc&G8
